---
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
read:
  replicas: 1
write:
  replicas: 1
monitoring:
  serviceMonitor:
    labels:
      release: "prometheus"
test:
  prometheusAddress: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local.:9090"
